import PageTemplate from '@/components/PageTemplate';

const locationData = { title: 'Digital Marketing Agency Weybridge', region: 'Weybridge', description: 'Expert digital marketing for Weybridge businesses.' };

export default function LocationPage() {
  const content = `<h2>Digital Marketing Services in ${locationData.region}</h2><p>${locationData.description}</p><h3>Why Local Digital Marketing Matters</h3><p>Businesses in ${locationData.region} face unique challenges and opportunities. Your customers are searching online. Your competitors are bidding on ads. The question is: are you visible when they search?</p><p>We help ${locationData.region} businesses:</p><ul><li>Get found in Google search results and Google Maps</li><li>Generate leads and sales through targeted ads</li><li>Build modern, fast websites that convert</li><li>Organize and nurture customer relationships</li></ul><h3>Our Complete Service Offering</h3><ul><li><strong>SEO &amp; Organic Search:</strong> Rank higher in Google and drive qualified traffic</li><li><strong>Google Ads &amp; PPC:</strong> Generate immediate leads with targeted paid campaigns</li><li><strong>Local SEO:</strong> Dominate local search and Google Maps in ${locationData.region}</li><li><strong>Web Design:</strong> Modern, conversion-focused websites that represent your business</li><li><strong>CRM Implementation:</strong> Organize customer relationships and automate sales processes</li></ul><h3>Local Expertise You Can Trust</h3><p>We're not a massive agency with cookie-cutter solutions. We understand the ${locationData.region} market. We know your competition. We know what works locally because we've helped dozens of businesses in your area succeed.</p><h3>Our Approach</h3><p><strong>1. Discovery:</strong> We audit your current online presence and understand your business goals.</p><p><strong>2. Strategy:</strong> We develop a custom digital marketing strategy tailored to your local market.</p><p><strong>3. Execution:</strong> We implement across all channels—SEO, ads, website, CRM.</p><p><strong>4. Growth:</strong> We monitor, optimize, and help you grow month after month.</p><h3>Ready to Grow Your Business in ${locationData.region}?</h3><p>We work with businesses of all sizes, from startups to established companies. Whether you need SEO, ads, a new website, or a complete digital marketing overhaul, we can help.</p>`;
  const benefits = [{ icon: '📍', title: 'Local Expertise', description: `We know the ${locationData.region} market and what works for local businesses.` }, { icon: '📈', title: 'Proven Results', description: `Dozens of ${locationData.region} businesses have grown with our help.` }, { icon: '💡', title: 'Strategic Approach', description: 'We build custom strategies aligned with your business goals.' }];
  return <PageTemplate title={locationData.title} description={`Helping ${locationData.region} businesses grow online with proven digital marketing strategies`} content={content} benefits={benefits} ctaText={`Get Your Free ${locationData.region} Digital Marketing Audit`} ctaHref="/contact-us" />;
}
